### ISSUE TITLE
安卓真机（华为荣耀，安卓7.0 微信版本6.7.2），随机出现绘制bug，偶尔正常 。未测试iphone

### ISSUE THREAD

**Issue by zeroHu** [AfanSama/easy-canvas#6]
**这个是正常的情况**

![image](https://user-images.githubusercontent.com/14057313/45015767-4a4bf200-b055-11e8-94d6-73755c8e729c.png)

**下面是随机出现的不正常的情况**

![image](https://user-images.githubusercontent.com/14057313/45015811-694a8400-b055-11e8-9858-091417276391.png)

求解惑~ 或者给个参考思路 ！ 谢谢 afansama 提供的这么好的工具和思路

怀疑是微信小程序的锅。。。或者是微信的锅，目前没啥证据[一脸不服气啊]，改了改afansama的esay-canva组件源码~ 去掉了bloder， 把数据的小数点情况处理然后，fillText 为空的时候不进行绘制
这个时候 console 出情况 所有都是正常显示 的 但是 console 写的明明setFontSize(30) 结果显示的贼小。。。。。心累一万年(手动滑稽)

**Comment by putaoZt** [comment]
安卓手机绘制text文本还是有不低的概率出现绘制出错的。条件是text的文案超出1行。第二行内容介于换行和不换行中间，这个时候比较容易复现。安卓华为p9绘制出错概率比较高

**Comment by xiaoyu214** [comment]
我也遇到了，华为有个机型偶尔会出现样式错乱的情况，最后解决方案是给draw中调用的saveImageToLocal方法加了定时器做了异步处理。目测还是异步绘制和成图的顺序问题。

**Comment by CoderAstro** [comment]
我也遇到这个问题
